static_marker_url: http://goo.gl/1jfSj

client_id: 154612174572644
secret_id: 1d805d27dd7492cfe3b2ce6f8c4ccbf5

facebook_link: http://goo.gl/y0Z7E

twitter_link: http://twitter/llfb

paypal_donate_html: >
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
    <input type="hidden" name="cmd" value="_s-xclick">
    <input type="hidden" name="hosted_button_id" value="FDNQJCZVW3MTN">
    <input type="image" src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
    <img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form>

facebook_like: >
    <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like show_faces="true" width="200" font="trebuchet ms"></fb:like>
