development:
  static_marker_url: http://goo.gl/1jfSj
  
  client_id: 175005175873101
  secret_id: 699e53c1d614ee4270a1df567040ac71

  facebook_link: http://goo.gl/y0Z7E

  twitter_link: http://goo.gl/gF9yo

  paypal_donate_html: >
      [paypal donate goes here]

  facebook_like: >
      [fb like goes here]
      
  twitter_tweet: >
      [tweet here]

  google_buzz: >
      [buzz here]
            
  #this is for posting to tweet everytime a new post appears, testing uses askmoby twitter acc
  twitter_consumer_key: r0QPYB4iEx6JhqoClRXA
  twitter_consumer_secret: 8stWeCiR5K4Q5DdAuOWPfhTg1wryXFVYz1yTOLZwjyo
  twitter_oauth_token: "103129028-2ekKmtTw8ojvN1v4hvTePz8WrALPKApyy0Fl3Cos"
  twitter_oauth_token_secret: DsoaOBK2vYZFMdP8K662EekOxtqsyNDjivVOLfV44
  
  #managing blogs, etc
  manager_alias: "1033864170" # supplying no manager_alias makes everyone a manager

#-------------------------------------------------------------------------------
production:
  static_marker_url: http://goo.gl/1jfSj

  client_id: 154612174572644
  secret_id: 1d805d27dd7492cfe3b2ce6f8c4ccbf5

  facebook_link: http://goo.gl/y0Z7E

  twitter_link: http://goo.gl/gF9yo

  paypal_donate_html: >
      <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
      <input type="hidden" name="cmd" value="_s-xclick">
      <input type="hidden" name="hosted_button_id" value="FDNQJCZVW3MTN">
      <input type="image" src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
      <!-- img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" -->
      </form>

  facebook_like: >
      <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like show_faces="true" width="200" font="trebuchet ms"></fb:like>
      
  twitter_tweet: >
      <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

  google_buzz: >
      <a title="Post to Google Buzz" class="google-buzz-button" href="http://www.google.com/buzz/post" data-button-style="small-count"></a>
      <script type="text/javascript" src="http://www.google.com/buzz/api/button.js"></script>    
      
  #this is for posting to tweet everytime a new post appears, production uses llfeedback twitter acc
  twitter_consumer_key: zwZWBVQjVcWGwgnA8n0y2Q
  twitter_consumer_secret: eQ7uvqDLOoPXPtXlm9ts1OqrdHxJIA0KgXGofV8bY
  twitter_oauth_token: 227477296-qIkXvZiqMvZD8q5xFoPWZB8lMsxJnuezHrYxVUI7
  twitter_oauth_token_secret: a1kl5uoFsK4YcRjno3U3jLXogg7e4Xg6DsZdYLrGw  
  
  #managing blogs, etc
  manager_alias: "1033864170"
